apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "symphony.fullname" . }}-hook-role
  labels:
    app: symphony-api
rules:
- apiGroups: ["symphony.microsoft.com"] 
  resources: ["targets", "instances", "solutionversions"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["solution.symphony"] 
  resources: ["instances", "solutionversions"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["workflow.symphony"] 
  resources: ["campaignversions", "activations"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["federation.symphony"] 
  resources: ["sites", "catalogversions"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["fabric.symphony"] 
  resources: ["devices", "targets"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["ai.symphony"] 
  resources: ["models", "skills", "skillpackages"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
  resourceNames: ["targets.symphony.microsoft.com", "instances.symphony.microsoft.com", "solutionversions.symphony.microsoft.com", "targets.fabric.symphony", "devices.fabric.symphony", "campaignversions.workflow.symphony", "activations.workflow.symphony", "instances.solution.symphony", "solutionversions.solution.symphony", "models.ai.symphony", "skills.ai.symphony", "skillpackages.ai.symphony", "sites.federation.symphony", "catalogversions.federation.symphony"]
