apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: tinyapp  
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: tinyapp-v1
spec:
  rootResource: tinyapp
  components:
  - name: wasm-module
    type: wasm
    properties:
      wasm.url: "https://github.com/Haishi2016/Vault818/releases/download/vtest/http-wasm.wasm"
      wasm.runtime: "wasmedge"
      wasm.dir: "/:/sys/kernel/debug/tracing"