apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: busybox  
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: busybox-v1
spec:  
  components:
  - name: busybox
    type: container
    properties:
      container.image: "redis:latest"