apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: tinyedge      
spec:  
  forceRedeploy: true
  topologies:
  - bindings:
    - role: instance
      provider: providers.target.staging
      config:
        inCluster: "true"   
        targetName: tiny-edge