apiVersion: solution.symphony/v1
kind: Instance
metadata:
  name: sample-prometheus-instance
spec:
  scope: sample-k8s-scope  
  solutionversion: sample-prometheus-server:v1
  target: 
    name: sample-k8s-target