apiVersion: solutionversion.symphony/v1
kind: Instance
metadata:
  name: multi-os-instance
spec:
  solutionversion: multi-os-solutionversion:version1
  target: 
    selector: 
      scenario: multi-os