apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: line2
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: line2-config
spec:
  rootResource: line2
  catalogType: config
  properties:
    line2:
      name: "Line 2"
      capacity: 200
