apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: gatedprometheusinstance
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: gatedprometheusinstance-v1
spec:
  rootResource: gatedprometheusinstance
  catalogType: instance
  properties:
    metadata:
      name: gatedprometheusinstance:v1
    spec: 
      solution: gatedprometheusserver:v1
      target:
        name: gatedk8starget