apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: mockcampaign
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: mockcampaign-v1
spec:
  rootResource: mockcampaign
  firstStage: "mock"
  selfDriving: true
  stages:
    mock:
      name: "mock"
      provider: "providers.stage.mock"
      inputs:
        foo: "${{$output(mock,foo)}}"
      stageSelector: "${{$if($lt($output(mock,foo), 5), mock, '')}}"