apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: sampleconfig
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: sampleconfig-v1
spec:
  rootResource: sampleconfig
  catalogType: config
  metadata:
    schema: sample-schema
  properties:
    foo: "foo@hotmail.com"
    bar: "15"