apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: sampleschema
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: sampleschema-v1
spec:
  rootResource: sampleschema
  catalogType: schema
  properties:
    spec:
      rules:
        foo:
          pattern: "<email>"
        bar:
          expression: "${{$and($gt($val(),10),$lt($val(),20))}}"