apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: countercampaign
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: countercampaign-v1
spec:
  rootResource: countercampaign
  firstStage: "counter"
  selfDriving: true
  stages:
    counter:
      name: "counter"
      provider: "providers.stage.counter"      
      stageSelector: "${{$if($lt($output(counter,val), 20), counter, '')}}"