apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: site-catalogversion
spec:  
---
apiVersion: federation.symphony/v1
kind: CatalogVersion
metadata:
  name: site-catalogversion-v-version1
spec:
  rootResource: site-catalogversion
  catalogType: catalogversion
  properties:
    metadata: 
      name: web-app-config:version1
    spec: 
      catalogType: config
      properties:
        image: "ghcr.io/eclipse-symphony/sample-flask-app:latest"
        serviceType: "LoadBalancer"