apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: helloworld
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: helloworld-v1
spec:
  rootResource: countercampaign
  firstStage: "mock"
  selfDriving: true
  stages:
    mock:
      name: "mock"
      provider: "providers.stage.mock"  