apiVersion: solutionversion.symphony/v1
kind: Instance
metadata:
  name: ankaios-app-instance
spec:
  solutionversion: ankaios-app:v1
  target: 
    name: ankaios-target
  reconciliationPolicy:
    interval: 1m