---
apiVersion: solution.symphony/v1
kind: Instance
metadata:
  name: reusable-segment-instance
spec:
  solutionversion: reusable-segment-solutionversion:v1
  scope: default
  target:
    name: k8s-target
