apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: testapp  
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata:
  name: testapp-v1
spec:
  rootResource: testapp
  components:
  - name: nginx
    type: container
    properties:
      container.image: "nginx"