apiVersion: solutionversion.symphony/v1
kind: Instance
metadata:
  name: sample-prometheus-instance
spec:
  scope: sample-local-scope  
  solutionversion: sample-prometheus-server:v1
  target: 
    name: sample-local-target