apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: sample-local-target 
spec:
  forceRedeploy: false
  topologies:
  - bindings:
    - role: instance
      provider: providers.target.docker
      config: