apiVersion: solution.symphony/v1
kind: Instance
metadata:
  name: factoryfloor1
spec:
  solution: factoryaivision:v1
  target:
    name: iotedgetarget
  topologies:
  - role: video
    selector:
      tag: "factory-floor-1"
    parameters:
      foo: bar


