##
## Copyright (c) Microsoft Corporation.
## Licensed under the MIT license.
## SPDX-License-Identifier: MIT
##
FROM --platform=$BUILDPLATFORM golang:1.20.2-alpine AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV CGO_ENABLED=0

RUN mkdir /workspace
COPY ./packages /workspace/packages
COPY ./coa /workspace/coa
COPY ./api /workspace/api
WORKDIR /workspace/api
# File permissions are not preserved when copying files in ADO. 
RUN chmod +x pkg/apis/v1alpha1/providers/target/script/mock-*.sh
RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} GODEBUG=netdns=cgo go build -o /dist/symphony-api

FROM ubuntu:latest
RUN \
    set -x \
    && apt-get update \
    && apt-get install -y openssl libssl-dev ca-certificates curl jq  android-tools-adb \
    && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
    && chmod +x get_helm.sh \
    && ./get_helm.sh \
    && apt upgrade -y
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO /zoneinfo.zip
COPY --from=build /dist /
ADD ./api/symphony-target-agent.json /
EXPOSE 8088
EXPOSE 8089
ENV LOG_LEVEL Debug
ENV CONFIG /symphony-target-agent.json
CMD exec /symphony-api -c $CONFIG -l $LOG_LEVEL


# ADO Docker file
# FROM --platform=$BUILDPLATFORM mcr.microsoft.com/oss/go/microsoft/golang:1.21-fips-cbl-mariner2.0 AS build

# ARG TARGETPLATFORM
# ARG BUILDPLATFORM
# ARG TARGETOS
# ARG TARGETARCH

# ENV CGO_ENABLED=0

# RUN mkdir /src
# WORKDIR /src
# COPY . .
 
# RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} GODEBUG=netdns=cgo go build -o /dist/symphony-agent  -tags=azure

# FROM mcr.microsoft.com/cbl-mariner/base/core:2.0
# RUN \
#     set -x \
#     && tdnf check-update \
#     && tdnf install -y ca-certificates openssl jq 
# # RUN tdnf install -y ffmpeg android-tools-adb

# COPY --from=build /dist /
# ADD ./api/symphony-target-agent.json /
# EXPOSE 8088
# EXPOSE 8089
# ENV LOG_LEVEL Debug
# ENV CONFIG /symphony-target-agent.json
# CMD exec /symphony-api -c $CONFIG -l $LOG_LEVEL
