FROM --platform=$BUILDPLATFORM mcr.microsoft.com/devcontainers/go AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV CGO_ENABLED=0

RUN mkdir /src
WORKDIR /src
COPY . .
 
RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} GODEBUG=netdns=cgo go build -o /dist/symphony-agent

FROM mcr.microsoft.com/cbl-mariner/base/core:2.0
RUN \
    set -x \
    && tdnf check-update \
    && tdnf install -y ca-certificates openssl jq 
# RUN tdnf install -y ffmpeg android-tools-adb

COPY --from=build /dist /
ADD ./symphony-agent.json /
EXPOSE 8088
EXPOSE 8089
ENV LOG_LEVEL Debug
ENV CONFIG /symphony-agent.json
CMD exec /symphony-agent -c $CONFIG -l $LOG_LEVEL