##
## Copyright (c) Microsoft Corporation.
## Licensed under the MIT license.
## SPDX-License-Identifier: MIT
##
FROM --platform=$BUILDPLATFORM golang:1.22.4-alpine AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG HELM_ARCH

RUN case "$TARGETARCH" in \
        "amd64") HELM_ARCH="linux-amd64" ;; \
        "arm64") HELM_ARCH="linux-arm64" ;; \
        "arm") HELM_ARCH="linux-arm" ;; \
        "386") HELM_ARCH="linux-386" ;; \
        *) echo "Unsupported architecture: $TARGETARCH" && exit 1 ;; \
    esac && echo "Using Helm architecture: $HELM_ARCH"

ENV CGO_ENABLED=0

RUN mkdir /workspace
COPY ./packages /workspace/packages
COPY ./coa /workspace/coa
COPY ./api /workspace/api
WORKDIR /workspace/api
# File permissions are not preserved when copying files in ADO. 
RUN chmod +x pkg/apis/v1alpha1/providers/target/script/mock-*.sh
RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} GODEBUG=netdns=cgo go build -o /dist/symphony-api

FROM ubuntu:latest

ARG HELM_ARCH

RUN \
    set -x \
    && apt-get update \
    && apt-get install -y openssl libssl-dev ca-certificates curl jq wget android-tools-adb \
    && wget https://get.helm.sh/helm-v3.16.2-$HELM_ARCH.tar.gz \
    && tar -zxvf helm-v3.16.2-$HELM_ARCH.tar.gz \
    && mv $HELM_ARCH/helm /usr/local/bin/helm \
    && apt upgrade -y
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO=/zoneinfo.zip
COPY --from=build /dist /
ADD ./api/symphony-target-agent.json /
EXPOSE 8088
EXPOSE 8089
ENV LOG_LEVEL=Debug
ENV CONFIG=/symphony-target-agent.json
CMD exec /symphony-api -c $CONFIG -l $LOG_LEVEL